FROM fedora
RUN dnf update -y && dnf upgrade -y
RUN dnf install -y libxcrypt-compat qemu-img osbuild osbuild-ostree
RUN mkdir -p "/usr/libexec/osbuild-composer"
RUN mkdir -p "/etc/osbuild-composer/"
RUN mkdir -p "/run/osbuild-composer/"
RUN mkdir -p "/var/cache/osbuild-worker/"
RUN mkdir -p "/var/lib/osbuild-composer/"
RUN mkdir -p "/var/cache/osbuild-composer/output"
COPY /bin/osbuild-worker /usr/libexec/osbuild-composer/
COPY ./dnf-json /usr/libexec/osbuild-composer/

ENTRYPOINT ["/usr/libexec/osbuild-composer/osbuild-worker", "172.16.0.1:8700"]
