FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL maintainer="gzuccare@redhat.com"

LABEL io.k8s.display-name="OSBUILD-COMPOSER minimal" \
      io.k8s.description="This is the base image for the osbuild-composer used in our Tekton pipeline"

RUN microdnf install -y python3 python3-dnf
RUN mkdir -p "/usr/libexec/osbuild-composer"
RUN mkdir -p "/etc/osbuild-composer/"
RUN mkdir -p "/run/osbuild-composer/"
RUN mkdir -p "/var/cache/osbuild-composer/"
RUN mkdir -p "/var/lib/osbuild-composer/"
RUN mkdir -p "/usr/share/osbuild-composer/"
RUN mkdir -p "/opt/migrate/"
COPY  /bin/osbuild-composer /usr/libexec/osbuild-composer/
COPY ./entrypoint.py /opt/entrypoint.py
COPY ./uid_entrypoint.sh ./uid_entrypoint.sh

EXPOSE 8080 8700

# execute using args (see deplyment) "python3" "/opt/entrypoint.py" "--remote-worker-api" "--composer-api" "--shutdown-wait-period" "15"]
ENTRYPOINT ["./uid_entrypoint.sh"]

