apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: composer-pvc
  namespace: osbuild
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
