apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer
  namespace: osbuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composer
  template:
    metadata:
      labels:
        app: composer
    spec:
      containers:
        - args:
            - "python3"  
            - "/opt/entrypoint.py"  
            - "--remote-worker-api" 
            - "--composer-api" 
            - "--shutdown-wait-period" 
            - "15" 
          image: quay.io/luzuccar/osbuild-composer:v1.0.0
          name: osbuild-composer-main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/osbuild-composer
              name: composer-volume
      volumes:
        - name: composer-volume
          persistentVolumeClaim:
            claimName: composer-pvc

