- op: replace
  path: "/spec/local"
  value:
    path: COMPOSER_PATH

- op: replace
  path: "/spec/nodeAffinity/required/nodeSelectorTerms/0"
  value:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - KUBEHOST
