apiVersion: v1
kind: Service
metadata:
  name: composer
  namespace: osbuild
spec:
  type: NodePort
  selector:
    app: composer
  ports:
    - name: worker-api
      protocol: TCP
      port: 8700
      targetPort: 8700
      nodePort: 30037
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30030
