[worker]
allowed_domains = [ "localhost", "worker.osbuild.org","worker.osbuild.svc.cluster.local" ]
ca = "/etc/osbuild-composer/ca-crt.pem"

[koji]
allowed_domains = [ "localhost", "worker.osbuild.org", "composer.osbuild.svc.cluster.local" ]
ca = "/etc/osbuild-composer/ca-crt.pem"
