[koji.localhost.kerberos]
principal = "osbuild-krb@LOCAL"
keytab = "/etc/osbuild-worker/client.keytab"

[generic_s3]
endpoint = "http://minio.osbuild.svc.cluster.local:9000"
region = "us-east-1"
bucket = "composer-minimal"
skip_ssl_verification = true
credentials = "/etc/osbuild-worker/creds"
